SPELL_CSPELL_DISABLE_ERRORS: true
REPOSITORY_KICS_DISABLE_ERRORS: true
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true
SPELL_LYCHEE_ARGUMENTS: --exclude "medium.com"
REPOSITORY_OSV_SCANNER_ARGUMENTS: --allow-no-lockfiles

SECURITY_SUGGESTIONS: false
FLAVOR_SUGGESTIONS: false

ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
